# Site settings
title: Geoff Hasson | Front-End Developer
email: geoff@ghasson.com
description: "This is my site, baby!"
baseurl: /jekyll
url: "http://yourdomain.com"
username: geoffhasson

# Build settings
markdown: kramdown
permalink: pretty
